In [257]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
from IPython.display import clear_output

In [2]:
s=pd.Series([1,3,4,np.nan,6,8])

In [3]:
s

0    1.0
1    3.0
2    4.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [5]:
dates=pd.date_range('20130101',periods=6)

In [6]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [16]:
columns=list('ABCD')
df=pd.DataFrame(np.random.randn(6,4),index=dates, columns=columns) # list() convert sth. to a list

In [17]:
df

A         B         C         D
2013-01-01  1.319272  0.664721 -0.175662 -0.501664
2013-01-02  0.026811 -0.439811  0.318826  0.093456
2013-01-03  0.037848 -0.047295 -1.171335 -0.321446
2013-01-04  0.080485 -0.418718 -0.007222  0.458247
2013-01-05  1.091478 -1.114008  0.556083 -0.965007
2013-01-06 -0.706324  2.821880 -1.463043 -0.015984

In [18]:
help(pd.DataFrame)

Help on class DataFrame in module pandas.core.frame:

class DataFrame(pandas.core.generic.NDFrame)
 |  Two-dimensional size-mutable, potentially heterogeneous tabular data
 |  structure with labeled axes (rows and columns). Arithmetic operations
 |  align on both row and column labels. Can be thought of as a dict-like
 |  container for Series objects. The primary pandas data structure.
 |  
 |  Parameters
 |  ----------
 |  data : numpy ndarray (structured or homogeneous), dict, or DataFrame
 |      Dict can contain Series, arrays, constants, or list-like objects
 |  
 |      .. versionchanged :: 0.23.0
 |         If data is a dict, argument order is maintained for Python 3.6
 |         and later.
 |  
 |  index : Index or array-like
 |      Index to use for resulting frame. Will default to RangeIndex if
 |      no indexing information part of input data and no index provided
 |  columns : Index or array-like
 |      Column labels to use for resulting frame. Will default to
 |      Ran

In [24]:
sys.modules(pd.core.frame)

TypeError: 'dict' object is not callable

In [25]:
pd.core.frame.__file__

'/Users/wandy/anaconda3/envs/NUSworkshop/lib/python3.6/site-packages/pandas/core/frame.py'

In [26]:
df2 = pd.DataFrame({ 'A' : 1., 'B' : pd.Timestamp('20130102'),  'C' : pd.Series(1,index=list(range(4)),dtype='float32'), 'D' : np.array([3] * 4,dtype='int32'),  'E' : pd.Categorical(["test","train","test","train"]), 'F' : 'foo' })

In [27]:
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [29]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [30]:
df.<TAB>

SyntaxError: invalid syntax (<ipython-input-30-e47a8920668a>, line 1)

In [31]:
df

A         B         C         D
2013-01-01  1.319272  0.664721 -0.175662 -0.501664
2013-01-02  0.026811 -0.439811  0.318826  0.093456
2013-01-03  0.037848 -0.047295 -1.171335 -0.321446
2013-01-04  0.080485 -0.418718 -0.007222  0.458247
2013-01-05  1.091478 -1.114008  0.556083 -0.965007
2013-01-06 -0.706324  2.821880 -1.463043 -0.015984

In [33]:
df.head(2)

A         B         C         D
2013-01-01  1.319272  0.664721 -0.175662 -0.501664
2013-01-02  0.026811 -0.439811  0.318826  0.093456

In [34]:
df.tail(2)

A         B         C         D
2013-01-05  1.091478 -1.114008  0.556083 -0.965007
2013-01-06 -0.706324  2.821880 -1.463043 -0.015984

In [35]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [36]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [37]:
df.values

array([[ 1.31927174,  0.66472064, -0.17566228, -0.50166391],
       [ 0.02681116, -0.43981144,  0.318826  ,  0.0934562 ],
       [ 0.03784825, -0.04729539, -1.17133535, -0.32144609],
       [ 0.08048463, -0.4187184 , -0.00722241,  0.45824701],
       [ 1.09147803, -1.11400844,  0.55608322, -0.96500714],
       [-0.70632368,  2.8218803 , -1.46304315, -0.0159839 ]])

In [39]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.308262  0.244461 -0.323726 -0.208733
std    0.757519  1.389842  0.815539  0.498758
min   -0.706324 -1.114008 -1.463043 -0.965007
25%    0.029570 -0.434538 -0.922417 -0.456609
50%    0.059166 -0.233007 -0.091442 -0.168715
75%    0.838730  0.486717  0.237314  0.066096
max    1.319272  2.821880  0.556083  0.458247

In [40]:
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    1.319272    0.026811    0.037848    0.080485    1.091478   -0.706324
B    0.664721   -0.439811   -0.047295   -0.418718   -1.114008    2.821880
C   -0.175662    0.318826   -1.171335   -0.007222    0.556083   -1.463043
D   -0.501664    0.093456   -0.321446    0.458247   -0.965007   -0.015984

In [54]:
df.sort_index(axis=0,ascending=False)

A         B         C         D
2013-01-06 -0.706324  2.821880 -1.463043 -0.015984
2013-01-05  1.091478 -1.114008  0.556083 -0.965007
2013-01-04  0.080485 -0.418718 -0.007222  0.458247
2013-01-03  0.037848 -0.047295 -1.171335 -0.321446
2013-01-02  0.026811 -0.439811  0.318826  0.093456
2013-01-01  1.319272  0.664721 -0.175662 -0.501664

In [55]:
df['A']

2013-01-01    1.319272
2013-01-02    0.026811
2013-01-03    0.037848
2013-01-04    0.080485
2013-01-05    1.091478
2013-01-06   -0.706324
Freq: D, Name: A, dtype: float64

In [56]:
df.A

2013-01-01    1.319272
2013-01-02    0.026811
2013-01-03    0.037848
2013-01-04    0.080485
2013-01-05    1.091478
2013-01-06   -0.706324
Freq: D, Name: A, dtype: float64

In [108]:
df[0:3]

A         B         C         D
2013-01-01  1.319272  0.664721 -0.175662 -0.501664
2013-01-02  0.026811 -0.439811  0.318826  0.093456
2013-01-03  0.037848 -0.047295 -1.171335 -0.321446

In [137]:
df[df.columns[0]+'1']=pd.Series((df.A)**2,index=df.index)
df=df.assign('a2'=pd.Series((df.A)**3))
print(df)

SyntaxError: keyword can't be an expression (<ipython-input-137-d1e5db1e6400>, line 2)

In [58]:
df.loc[dates[0]]

A    1.319272
B    0.664721
C   -0.175662
D   -0.501664
Name: 2013-01-01 00:00:00, dtype: float64

In [59]:
df.loc[:,['A','B']]

A         B
2013-01-01  1.319272  0.664721
2013-01-02  0.026811 -0.439811
2013-01-03  0.037848 -0.047295
2013-01-04  0.080485 -0.418718
2013-01-05  1.091478 -1.114008
2013-01-06 -0.706324  2.821880

In [62]:
df.loc[dates[0]:dates[2],['A','B']]

A         B
2013-01-01  1.319272  0.664721
2013-01-02  0.026811 -0.439811
2013-01-03  0.037848 -0.047295

In [65]:
df.loc[:,['A']]

A
2013-01-01  1.319272
2013-01-02  0.026811
2013-01-03  0.037848
2013-01-04  0.080485
2013-01-05  1.091478
2013-01-06 -0.706324

In [66]:
df.iloc[3]

A    0.080485
B   -0.418718
C   -0.007222
D    0.458247
Name: 2013-01-04 00:00:00, dtype: float64

In [67]:
df.iloc[3:5,0:2]

A         B
2013-01-04  0.080485 -0.418718
2013-01-05  1.091478 -1.114008

In [68]:
df.iloc[[1,2,4],[0,2]]

A         C
2013-01-02  0.026811  0.318826
2013-01-03  0.037848 -1.171335
2013-01-05  1.091478  0.556083

In [69]:
df.iloc[1:3,:]

A         B         C         D
2013-01-02  0.026811 -0.439811  0.318826  0.093456
2013-01-03  0.037848 -0.047295 -1.171335 -0.321446

In [70]:
import numpy as np
import matplotlib.pyplot as plt


def f(t):
    return np.exp(-t) * np.cos(2*np.pi*t)


t1 = np.arange(0.0, 3.0, 0.01)

ax1 = plt.subplot(212)
ax1.margins(0.05)           # Default margin is 0.05, value 0 means fit
ax1.plot(t1, f(t1), 'k')

ax2 = plt.subplot(221)
ax2.margins(2, 2)           # Values >0.0 zoom out
ax2.plot(t1, f(t1), 'r')
ax2.set_title('Zoomed out')

ax3 = plt.subplot(222)
ax3.margins(x=0, y=-0.25)   # Values in (-0.5, 0.0) zooms in to center
ax3.plot(t1, f(t1), 'g')
ax3.set_title('Zoomed in')

plt.show()

In [71]:
test=np.random.randn(8)

In [72]:
test

array([ 1.71539629, -0.02405072, -0.39425724, -0.66551012, -1.34715198,
        0.45840244,  0.92281902, -0.69324765])

In [93]:
test=np.arange(0,100)
print(test)
np.random.shuffle(test)
print(test)
print(test[2:5])

idxd=np.arange(0,100)
np.random.shuffle(idxd)
print(idxd)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 4 24 63 94 47  0 27 91  2 97 66 71 41 56 35 31  5 70 89 82 13 37 19 25
 20 62 29 33 96 59  8  9 36 69 32 26 14 83 54 72 60 81 73 75 86 40 15 45
 57 98 99 46 58 10 77 55 51 79 17 12 21 16  1 38 43 53 80 49 95 52 78  7
  6 92  3 88 74 42 76 23 93 90 68 22 18 11 87 39 61 28 34 48 65 67 85 30
 64 50 84 44]
[63 94 47]
[67  0  3 11 65 87 37 73 81 90 97 17 74 53  4  2 88 82 61 52 34 14  7 64
  5 24 55 86 68 48 56 62 10  9 31 44 30 95 18 36  6 42 25 33 66 38 94 59
 22 92 80 63 43 49 50 93 98 45 15 57 23  8 46 16 76 19 77 96 28 40 47 70
 60 99 51 83 58 27 41 72 78 84 20 89  1 35 26 13 54 12 21 85 39 71 75 91
 32 69 29 79]


In [94]:
floor(0.9)

NameError: name 'floor' is not defined

In [99]:
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(10)

plt.figure()
plt.gca().set_color_cycle(['red', 'green', 'blue', 'yellow'])

plt.plot(x, x)
plt.plot(x, 2 * x)
plt.plot(x, 3 * x)
plt.plot(x, 4 * x)

plt.legend(['y = x', 'y = 2x', 'y = 3x', 'y = 4x'], loc='upper left')

plt.show()

/Users/wandy/anaconda3/envs/NUSworkshop/lib/python3.6/site-packages/ipykernel_launcher.py:7: MatplotlibDeprecationWarning: The set_color_cycle function was deprecated in version 1.5. Use `.set_prop_cycle` instead.
  import sys


In [106]:
a=range(0,4)
print(list(a))

[0, 1, 2, 3]


In [107]:
def square(x,y):
    return x*x, y*y

t = square(2,3)
print(t)  # Produces (4,9)
# Now access the tuple with usual operations

(4, 9)


In [124]:
points = [{'x': 2, 'y': 3},
          {'x': 4, 'y': 1}]
points.sort(key=lambda i: i['y'])
print(points)

[{'x': 4, 'y': 1}, {'x': 2, 'y': 3}]


In [142]:
N = 2
a = np.random.rand(N,N)
b = np.zeros((N,N+1))
b[:,1:] = a

In [143]:
print(b)

[[0.         0.02985395 0.98188584]
 [0.         0.25867158 0.31870832]]


In [144]:
 def input_password():
 
    # 提示用户输入密码
    pwd = input("请输入密码：")
 
    # 如果密码长度>=8,返回用户输入的密码
    if len(pwd) >= 8:
        return pwd
 
    # 如果 < 8 主动抛出异常
    print("主动抛出异常")
    # 1> 创建异常对象
    ex = Exception("密码长度不够")
 
    # 2> raise 主动抛出异常
    raise ex
 
 
# 提示用户输入密码
try:
    print(input_password())
except Exception as result:
    print(result)



请输入密码：ladf
主动抛出异常
密码长度不够


In [146]:
class DatabaseException(Exception):
    def __init__(self,err='数据库错误'):
        Exception.__init__(self,err)

class PreconditionsException(DatabaseException):
    def __init__(self,err='PreconditionsErr'):
        DatabaseException.__init__(self,err)

def testRaise():
    raise PreconditionsException()

try:
    testRaise()
except PreconditionsException as e:
    print (e)


PreconditionsErr


In [149]:
L=np.eye(3)
L[0,0]=0
print(L)

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [150]:
10*L

array([[ 0.,  0.,  0.],
       [ 0., 10.,  0.],
       [ 0.,  0., 10.]])

In [158]:
beta_range=np.geomspace(0.001,100, num = 11, endpoint = True, dtype=np.float64)
beta_range=np.insert(beta_range,0,0)
beta_range
theta_reg=np.zeros(beta_range.shape)
theta_reg

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [171]:
my_list = beta_range
for c, value in enumerate(my_list):
    print(c)
    
np.zeros(3)

0
1
2
3
4
5
6
7
8
9
10
11


array([0., 0., 0.])

In [172]:
degree = 2
print(degree)

2


In [176]:
a=list(range(0,5))
print(a)

[0, 1, 2, 3, 4]


In [178]:
a.sum

AttributeError: 'list' object has no attribute 'sum'

In [191]:
a=list(range(0,1))
print(a)


[0]


In [222]:
x = [1, 2, 3]
def inc(x):
    x[1] += 10
inc(x)
print(x)



[1, 12, 3]


In [223]:
x = 1
def inc(x):
    x += 5
inc(x)
print(x)

1


In [195]:
def foo():
    x = 20

    def bar():
        global x
        x = 25
    
    print("Before calling bar: ", x)
    print("Calling bar now")
    bar()
    print("After calling bar: ", x)

foo()
print("x in main : ", x)

Before calling bar:  20
Calling bar now
After calling bar:  20
x in main :  25


In [208]:
import time
import threading

t_start=time.time()
class MyThread(threading.Thread):
    def run(self):
        for i in range(5):
            print('thread {}, @number: {}'.format(self.name, i))
            time.sleep(1)

def main():
    print("Start main threading")
    # 创建三个线程
    threads = [MyThread() for i in range(3)]
    # 启动三个线程
    for t in threads:
#         t.daemon=True
        t.start()
#     for t in threads:
    for t in threads:
        t.join()

    print("End Main threading")
    print(time.time() - t_start)


if __name__ == '__main__':
    main()

Start main threading
thread Thread-38, @number: 0
thread Thread-39, @number: 0
thread Thread-40, @number: 0
thread Thread-39, @number: 1thread Thread-38, @number: 1
thread Thread-40, @number: 1

thread Thread-39, @number: 2thread Thread-38, @number: 2
thread Thread-40, @number: 2

thread Thread-38, @number: 3
thread Thread-39, @number: 3
thread Thread-40, @number: 3
thread Thread-38, @number: 4thread Thread-39, @number: 4

thread Thread-40, @number: 4
End Main threading
5.027444839477539


In [210]:
   error_cv_reg_multismpl=np.zeros(10)

In [213]:
t_start=time.time()
def foo():
    x = 20

    def bar():
        global x
        x = 25
    
    print("Before calling bar: ", x)
    print("Calling bar now")
    bar()
    print("After calling bar: ", x)

foo()
print("x in main : ", x)
t_end=time.time()
print(f'The time cost is {t_end-t_start}s')

Before calling bar:  20
Calling bar now
After calling bar:  20
x in main :  25
The time cost is 0.0017058849334716797s


In [226]:
import multiprocessing
import time

def proc1(pipe):
    while True:
        for i in range(10000):
            print("send: %s" %(i))
            pipe.send(i)
            time.sleep(1)

def proc2(pipe):
    while True:
        print("proc2 rev:", pipe.recv())
        time.sleep(1)

def proc3(pipe):
    while True:
        print("PROC3 rev:", pipe.recv())
        time.sleep(1)

if __name__ == "__main__":
    pipe = multiprocessing.Pipe()
    p1 = multiprocessing.Process(target=proc1, args=(pipe[0],))
    p2 = multiprocessing.Process(target=proc2, args=(pipe[1],))
    p3 = multiprocessing.Process(target=proc3, args=(pipe[1],))

    p1.start()
    p2.start()
    p3.start()

    p1.join()
    p2.join()
    p3.join()

send: 0
proc2 rev: 0
send: 1


Process Process-4:
Traceback (most recent call last):
  File "/Users/wandy/anaconda3/envs/NUSworkshop/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/wandy/anaconda3/envs/NUSworkshop/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-226-a8f49b800bf6>", line 13, in proc2
    print("proc2 rev:", pipe.recv())
  File "/Users/wandy/anaconda3/envs/NUSworkshop/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
EOFError: Ran out of input


send: 2


Process Process-5:
Traceback (most recent call last):
  File "/Users/wandy/anaconda3/envs/NUSworkshop/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/wandy/anaconda3/envs/NUSworkshop/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-226-a8f49b800bf6>", line 18, in proc3
    print("PROC3 rev:", pipe.recv())
  File "/Users/wandy/anaconda3/envs/NUSworkshop/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
_pickle.UnpicklingError: unpickling stack underflow


send: 3
send: 4
send: 5
send: 6
send: 7
send: 8
send: 9


Process Process-3:
Traceback (most recent call last):
  File "/Users/wandy/anaconda3/envs/NUSworkshop/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/wandy/anaconda3/envs/NUSworkshop/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-226-a8f49b800bf6>", line 9, in proc1
    time.sleep(1)
KeyboardInterrupt


KeyboardInterrupt: 

In [227]:
def f():
    return True, False
x, y = f()
print(x)
print(y)

True
False


In [229]:
import multiprocessing
import os, time, random

def Lee():
    print("\nRun task Lee-%s" %(os.getpid())) #os.getpid()获取当前的进程的ID
    start = time.time()
    time.sleep(random.random() * 10) #random.random()随机生成0-1之间的小数
    end = time.time()
    print('Task Lee, runs %0.2f seconds.' %(end - start))

def Marlon():
    print("\nRun task Marlon-%s" %(os.getpid()))
    start = time.time()
    time.sleep(random.random() * 40)
    end=time.time()
    print('Task Marlon runs %0.2f seconds.' %(end - start))

def Allen():
    print("\nRun task Allen-%s" %(os.getpid()))
    start = time.time()
    time.sleep(random.random() * 30)
    end = time.time()
    print('Task Allen runs %0.2f seconds.' %(end - start))

def Frank():
    print("\nRun task Frank-%s" %(os.getpid()))
    start = time.time()
    time.sleep(random.random() * 20)
    end = time.time()
    print('Task Frank runs %0.2f seconds.' %(end - start))

if __name__=='__main__':
    function_list=  [Lee, Marlon, Allen, Frank] 
    print("parent process %s" %(os.getpid()))

    pool=multiprocessing.Pool(4)
    for func in function_list:
        pool.apply_async(func)     #Pool执行函数，apply执行函数,当有一个进程执行完毕后，会添加一个新的进程到pool中

    print('Waiting for all subprocesses done...')
    pool.close()
    pool.join()    #调用join之前，一定要先调用close() 函数，否则会出错, close()执行后不会有新的进程加入到pool,join函数等待素有子进程结束
    print('All subprocesses done.')

parent process 49616

Run task Frank-95175
Run task Marlon-95172
Run task Allen-95174
Run task Lee-95173



Waiting for all subprocesses done...
Task Lee, runs 5.59 seconds.
Task Frank runs 16.60 seconds.
Task Allen runs 26.50 seconds.
Task Marlon runs 31.04 seconds.
All subprocesses done.


In [232]:
import curses
import time

def report_progress(filename, progress):
    """progress: 0-10"""
    stdscr.addstr(0, 0, "Moving file: {0}".format(filename))
    stdscr.addstr(1, 0, "Total progress: [{1:10}] {0}%".format(progress * 10, "#" * progress))
    stdscr.refresh()

if __name__ == "__main__":
    stdscr = curses.initscr()
    curses.noecho()
    curses.cbreak()

    try:
        for i in range(10):
            report_progress("file_{0}.txt".format(i), i+1)
            time.sleep(0.5)
    finally:
        curses.echo()
        curses.nocbreak()
        curses.endwin()

In [233]:
import progressbar
from time import sleep
bar = progressbar.ProgressBar(maxval=20, \
    widgets=[progressbar.Bar('=', '[', ']'), ' ', progressbar.Percentage()])
bar.start()
for i in xrange(20):
    bar.update(i+1)
    sleep(0.1)
bar.finish()

ModuleNotFoundError: No module named 'progressbar'

In [234]:
for i in range(100):
    time.sleep(1)
    sys.stdout.write("\r%d%%" %i)    # or print >> sys.stdout, "\r%d%%" %i,
    sys.stdout.flush()

8%

KeyboardInterrupt: 

In [237]:
import time
import sys

toolbar_width = 40

# setup toolbar
sys.stdout.write("[%s]" % (" " * toolbar_width))
sys.stdout.flush()
sys.stdout.write("\b" * (toolbar_width+1)) # return to start of line, after '['

for i in range(toolbar_width):
    time.sleep(0.1) # do real work here
    # update the bar
    sys.stdout.write("-")
    sys.stdout.flush()

sys.stdout.write("\n")

[                                        ----------------------------------------


In [239]:
# Print iterations progress
def printProgressBar (iteration, total, prefix = '', suffix = '', decimals = 1, length = 100, fill = '█'):
    """
    Call in a loop to create terminal progress bar
    @params:
        iteration   - Required  : current iteration (Int)
        total       - Required  : total iterations (Int)
        prefix      - Optional  : prefix string (Str)
        suffix      - Optional  : suffix string (Str)
        decimals    - Optional  : positive number of decimals in percent complete (Int)
        length      - Optional  : character length of bar (Int)
        fill        - Optional  : bar fill character (Str)
    """
    percent = ("{0:." + str(decimals) + "f}").format(100 * (iteration / float(total)))
    filledLength = int(length * iteration // total)
    bar = fill * filledLength + '-' * (length - filledLength)
    print('\r%s |%s| %s%% %s' % (prefix, bar, percent, suffix), end = '\r')
    # Print New Line on Complete
    if iteration == total: 
        print()

# 
# Sample Usage
# 

from time import sleep

# A List of Items
items = list(range(0, 57))
l = len(items)

# Initial call to print 0% progress
printProgressBar(0, l, prefix = 'Progress:', suffix = 'Complete', length = 50)
for i, item in enumerate(items):
    # Do stuff...
    sleep(0.1)
    # Update Progress Bar
    printProgressBar(i + 1, l, prefix = 'Progress:', suffix = 'Complete', length = 50)

Progress: |██████████████████████████████████████████████████| 100.0% Complete


In [240]:
import time, sys

# update_progress() : Displays or updates a console progress bar
## Accepts a float between 0 and 1. Any int will be converted to a float.
## A value under 0 represents a 'halt'.
## A value at 1 or bigger represents 100%
def update_progress(progress):
    barLength = 10 # Modify this to change the length of the progress bar
    status = ""
    if isinstance(progress, int):
        progress = float(progress)
    if not isinstance(progress, float):
        progress = 0
        status = "error: progress var must be float\r\n"
    if progress < 0:
        progress = 0
        status = "Halt...\r\n"
    if progress >= 1:
        progress = 1
        status = "Done...\r\n"
    block = int(round(barLength*progress))
    text = "\rPercent: [{0}] {1}% {2}".format( "#"*block + "-"*(barLength-block), progress*100, status)
    sys.stdout.write(text)
    sys.stdout.flush()


# update_progress test script
print("progress : 'hello'")
update_progress("hello")
time.sleep(1)

print("progress : 3")
update_progress(3)
time.sleep(1)

print("progress : [23]")
update_progress([23])
time.sleep(1)

print("")
print("progress : -10")
update_progress(-10)
time.sleep(2)

print("")
print("progress : 10")
update_progress(10)
time.sleep(2)

print("")
print("progress : 0->1")
for i in range(100):
    time.sleep(0.1)
    update_progress(i/100.0)

print("")
print("Test completed")
time.sleep(10)

progress : 'hello'
Percent: [----------] 0% error: progress var must be float
progress : 3
Percent: [##########] 100% Done...
progress : [23]
Percent: [----------] 0% error: progress var must be float

progress : -10
Percent: [----------] 0% Halt...

progress : 10
Percent: [##########] 100% Done...

progress : 0->1
Percent: [##########] 99.0% 99999999999%  
Test completed


In [244]:
percent = ("{0:." + str(1) + "f}").format(100 * (2 / float(100)))
print(percent)

2.0


In [245]:
str(1)

'1'

In [254]:
print('\rRun: %s ; '% (20), end='\r')
print('\rRun: %s ; '% (25), end='\r')
clear = lambda : os.system('cls')

In [258]:
from time import sleep
import sys

for i in range(21):
    sys.stdout.write('\r')
    # the exact output you're looking for:
    sys.stdout.write("[%-20s] %d%%" % ('='*i, 5*i))
    sys.stdout.flush()
    sleep(0.1)

clear_output()

In [252]:
import progressbar
from time import sleep
bar = progressbar.ProgressBar(maxval=20, \
    widgets=[progressbar.Bar('=', '[', ']'), ' ', progressbar.Percentage()])
bar.start()
for i in xrange(20):
    bar.update(i+1)
    sleep(0.1)
bar.finish()


ModuleNotFoundError: No module named 'progressbar'

In [260]:
from reprint import output
import time
import random

print("start the output")

with output(initial_len=3, interval=0) as output_lines:
    while True:
        output_lines[0] = "First_line  {}...".format(random.randint(1,10))
        output_lines[1] = "Second_line {}...".format(random.randint(1,10))
        output_lines[2] = "Third_line  {}...".format(random.randint(1,10))
        time.sleep(0.5)

start the output
Not in terminal, reprint now using normal build-in print function.
First_line  4...
Second_line 8...
Third_line  1...
First_line  8...
Second_line 10...
Third_line  3...
First_line  3...
Second_line 2...
Third_line  5...
First_line  3...
Second_line 4...
Third_line  7...
First_line  2...
Second_line 3...
Third_line  5...
First_line  3...
Second_line 5...
Third_line  7...
First_line  10...
Second_line 3...
Third_line  5...
First_line  7...
Second_line 7...
Third_line  7...
First_line  2...
Second_line 5...
Third_line  4...
First_line  4...
Second_line 3...
Third_line  9...
First_line  3...
Second_line 8...
Third_line  7...
First_line  7...
Second_line 3...
Third_line  10...
First_line  6...
Second_line 1...
Third_line  10...
First_line  10...
Second_line 6...
Third_line  5...
First_line  4...
Second_line 9...
Third_line  1...
First_line  6...
Second_line 4...
Third_line  3...
First_line  7...
Second_line 5...
Third_line  8...
First_line  7...
Second_line 5...
Third_line

KeyboardInterrupt: 

In [261]:
import curses
import time

def report_progress(filename, progress):
    """progress: 0-10"""
    stdscr.addstr(0, 0, "Moving file: {0}".format(filename))
    stdscr.addstr(1, 0, "Total progress: [{1:10}] {0}%".format(progress * 10, "#" * progress))
    stdscr.refresh()

if __name__ == "__main__":
    stdscr = curses.initscr()
    curses.noecho()
    curses.cbreak()

    try:
        for i in range(10):
            report_progress("file_{0}.txt".format(i), i+1)
            time.sleep(0.5)
    finally:
        curses.echo()
        curses.nocbreak()
        curses.endwin()